export const FONT_OPTIONS = [
  { name: 'Albert Sans', value: 'Albert Sans' },
  { name: 'Alegreya', value: 'Alegreya' },
  { name: 'Anybody', value: 'Anybody' },
  { name: 'Archivo', value: 'Archivo' },
  { name: 'Assistant', value: 'Assistant' },
  { name: 'Barlow', value: 'Barlow' },
  { name: 'Blinker', value: 'Blinker' },
  { name: 'Cabin', value: 'Cabin' },
  { name: 'Commissioner', value: 'Commissioner' },
  { name: 'Crimson Pro', value: 'Crimson Pro' },
  { name: 'DM Sans', value: 'DM Sans' },
  { name: 'Epilogue', value: 'Epilogue' },
  { name: 'Figtree', value: 'Figtree' },
  { name: 'Fuggles', value: 'Fuggles' },
  { name: 'Heebo', value: 'Heebo' },
  { name: 'IBM Plex Sans', value: 'IBM Plex Sans' },
  { name: 'IBM Plex Serif', value: 'IBM Plex Serif' },
  { name: 'Inter', value: 'Inter' },
  { name: 'Karla', value: 'Karla' },
  { name: 'Khand', value: 'Khand' },
  { name: 'Lato', value: 'Lato' },
  { name: 'Libre Baskerville', value: 'Libre Baskerville' },
  { name: 'Lora', value: 'Lora' },
  { name: 'Manrope', value: 'Manrope' },
  { name: 'Maven Pro', value: 'Maven Pro' },
  { name: 'Merriweather', value: 'Merriweather' },
  { name: 'Montserrat', value: 'Montserrat' },
  { name: 'Mukta', value: 'Mukta' },
  { name: 'Noto Sans', value: 'Noto Sans' },
  { name: 'Noto Serif', value: 'Noto Serif' },
  { name: 'Nunito', value: 'Nunito' },
  { name: 'Open Sans', value: 'Open Sans' },
  { name: 'Oswald', value: 'Oswald' },
  { name: 'Outfit', value: 'Outfit' },
  { name: 'Playfair Display', value: 'Playfair Display' },
  { name: 'Plus Jakarta Sans', value: 'Plus Jakarta Sans' },
  { name: 'Poppins', value: 'Poppins' },
  { name: 'Prompt', value: 'Prompt' },
  { name: 'Public Sans', value: 'Public Sans' },
  { name: 'Raleway', value: 'Raleway' },
  { name: 'Roboto', value: 'Roboto' },
  { name: 'Roboto Flex', value: 'Roboto Flex' },
  { name: 'Rubik', value: 'Rubik' },
  { name: 'Saira', value: 'Saira' },
  { name: 'Space Grotesk', value: 'Space Grotesk' },
  { name: 'Space Mono', value: 'Space Mono' },
  { name: 'Spectral', value: 'Spectral' },
  { name: 'Teko', value: 'Teko' },
  { name: 'Tilt Neon', value: 'Tilt Neon' },
  { name: 'Tilt Prism', value: 'Tilt Prism' },
  { name: 'Unbounded', value: 'Unbounded' },
  { name: 'Urbanist', value: 'Urbanist' },
  { name: 'Work Sans', value: 'Work Sans' },
].sort((a, b) => a.name.localeCompare(b.name));

export const FONT_WEIGHTS = [
  { name: 'Thin', value: '100' },
  { name: 'Extra Light', value: '200' },
  { name: 'Light', value: '300' },
  { name: 'Regular', value: '400' },
  { name: 'Medium', value: '500' },
  { name: 'Semi Bold', value: '600' },
  { name: 'Bold', value: '700' },
  { name: 'Extra Bold', value: '800' },
  { name: 'Black', value: '900' },
];
